name: flightbooking
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  velocity_x: ^4.2.1
  flutter_screenutil: ^5.9.0
  # get_cli: ^1.8.4
  http: ^0.13.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_easyloading: ^3.0.5
  shared_preferences: ^2.2.2
  flutter_spinkit: ^5.2.0
  path_provider_foundation: ^2.3.2
  path_provider: ^2.0.1
  webview_flutter: ^4.7.0
  country_picker: ^2.0.25
  dots_indicator: ^3.0.0
  flutter_date_range_picker: ^0.1.1
  flutter_credit_card: ^4.0.1
  emoji_alert: ^1.1.0
  custom_date_range_picker: ^1.0.10
  shimmer: ^3.0.0


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets:
  - assets/
  - assets/images/
  - assets/icons/
  uses-material-design: true
  



